version: '3'
services:
  harness-demo-app:
    container_name: harness-demo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "3000:3000"
    volumes:
      - ./.:/var/app
    restart: always